//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSales.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseSales.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addressOrderAsc.
        /// </summary>
        public static string TXT_ADDRESS_ORDER_ASC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_ADDRESS_ORDER_ASC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addressOrderDesc.
        /// </summary>
        public static string TXT_ADDRESS_ORDER_DESC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_ADDRESS_ORDER_DESC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formFilter.
        /// </summary>
        public static string TXT_FILTER_INPUT_FORM_NAME {
            get {
                return ResourceManager.GetString("TXT_FILTER_INPUT_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The postcode entered must be between 3-8 characters and contain the separating space..
        /// </summary>
        public static string TXT_INVALID_POSTCODE_FORMAT {
            get {
                return ResourceManager.GetString("TXT_INVALID_POSTCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastSaleOrderAsc.
        /// </summary>
        public static string TXT_LAST_SALE_ORDER_ASC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_LAST_SALE_ORDER_ASC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastSaleOrderDesc.
        /// </summary>
        public static string TXT_LAST_SALE_ORDER_DESC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_LAST_SALE_ORDER_DESC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderbydirection.
        /// </summary>
        public static string TXT_ORDER_BY_DIRECTION_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_ORDER_BY_DIRECTION_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderbyfield.
        /// </summary>
        public static string TXT_ORDER_BY_FIELD_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_ORDER_BY_FIELD_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string TXT_PAGE_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_PAGE_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageLink.
        /// </summary>
        public static string TXT_PAGE_LINK_PREFIX {
            get {
                return ResourceManager.GetString("TXT_PAGE_LINK_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodSelect.
        /// </summary>
        public static string TXT_PERIOD_DROPDOWN_NAME {
            get {
                return ResourceManager.GetString("TXT_PERIOD_DROPDOWN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postcode.
        /// </summary>
        public static string TXT_POSTCODE_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_POSTCODE_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostcodeInvalid.
        /// </summary>
        public static string TXT_POSTCODE_INVALID_VIEWDATA_KEY {
            get {
                return ResourceManager.GetString("TXT_POSTCODE_INVALID_VIEWDATA_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricePaidOrderAsc.
        /// </summary>
        public static string TXT_PRICE_PAID_ORDER_ASC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_PRICE_PAID_ORDER_ASC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pricePaidOrderDesc.
        /// </summary>
        public static string TXT_PRICE_PAID_ORDER_DESC_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_PRICE_PAID_ORDER_DESC_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeSelect.
        /// </summary>
        public static string TXT_PROPERTY_TYPE_DROPDOWN_NAME {
            get {
                return ResourceManager.GetString("TXT_PROPERTY_TYPE_DROPDOWN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propertyType.
        /// </summary>
        public static string TXT_PROPERTY_TYPE_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_PROPERTY_TYPE_INPUT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searchButton.
        /// </summary>
        public static string TXT_SEARCH_BUTTON_NAME {
            get {
                return ResourceManager.GetString("TXT_SEARCH_BUTTON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period.
        /// </summary>
        public static string TXT_SEARCH_PERIOD_INPUT_NAME {
            get {
                return ResourceManager.GetString("TXT_SEARCH_PERIOD_INPUT_NAME", resourceCulture);
            }
        }
    }
}
